language: python

dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install: make init

script: make ci

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: WrSI1sAWIViVnmXJA1duMVmE5+qJs0vZrmfQFVQfv2qVvIFhISYwSK/6FLS/OvngncdH2vY8eWhuC8D85udiO1pmfU9B1hVzemwJlzKNnlybiQqxfA9WV6saLh9A2h7VfAxniPpctl+bJ4gPtD+MZgM7NRLrvtZ5PWTwrR/WEL9flPlLBae3uMYj4qqkOPiTGyZseSz46e46VGmGJsGq0i1Yq0WAp4MMoS+HlhBeAaVwFwHKrn8KvEmtYYQfYub1DT3MqRhsKI8GPt1AdI8BEBUVEewE9KabYw7Re4RQ4dfHgzhvO2r+7+wH8t9hVrvgnREowAfQzRBs/NMM61yGeaiTH1ZJwmjHPuz5lfuyvBJ3KESLUWyjlBOYeuTh8vRV53vECwL4UwOojZLCoBqdmLDR3AWgrgnebXy5I8f0ZIwv8j9SZdTSrbXLxdxWEETgumsL+oJZKu8RZIIBgTKluQAV0NLhREFIe+rOyCEDrAQrOy/Yk4dch0TUNJwnZAGKNmtoyV7wgwDrOTsXnGCRLp9OFngdpMELEaTwpMJL8gupc5DnXvnLgW/ZAFb5B+9/cKH/xm2XK2P9yQf+Co7ZZhHRFhuu0J2Tcsil5zPwk1W+3OSgKcERRMBR6S5Hu+RgZXHHRbH626DCLz5221+oa67vB8d+pEMB/5chpRIiSm4=
