language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install: make init

script: make ci

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: xPZ71rI3b9uOTLYwUKJLyI/o4/NLUI1tXNX2/kIqZT9HLGrzIgsSmx8m2o+B3RyfhO7TzcvrGl7pkp4DFAheEhsngs1eUtGeNaOc07J5FqOLbUC2/gkL0eBTMHk9BWx0erMRNrX3dqCSdVMJrLHNNpqS1T8eU8jPYOipMCT7fUzoEDEe31qPxuIAbG0uq1GsB/kQtR6U8O28lNOk8Dx0F2BiD4UlQwNkt7ZLkFwQczshWXclxDq9fCGJyCiJveI+OGYhyNYTHoAvXTI30svCxAvbM1xr3dHkKMjwEsF8ZHSUh9juvLIhAH6s6vj5WotnZfSeso5m2c/yXNdcR2q2nw0xA3paF3P7QHMWeDEpdZTqcpU7W0eqa1vguwqmyltD6LYzhqZB/Qjq8O/tE6/csxV90vtbV+22RxCv8qMc/Br2IeVZM3mvVocbn7WKB4Mk44DlUO5wSNqObnoutoDarCd6CNO3osNH3/nNBhjojT0yT5u5ikrM/UmUDNwmZRVzh/2s7u3YzXldV1Z91+SIpgieUw4uD7jW6p/smyrcXBcLf3gEby/ynPrvk39d1EA9jPsTefHqDvGzxgaEhRoUNO2KNGYB/AFWOZ2Fyt48n3aw8kuEsB6w4VdqlTlx7eQAp3gj0OXvHe0XlcuzdXz4fURIpL+McdVcRMvCo4lWeVA=
